version: "3.9"

services:
  server:
    build:
      target: prod
    environment:
      - SERVER_HOST_NAME=$SERVER_HOST_NAME
  nginx:
    build:
      dockerfile: Dockerfile
      target: nginx
    volumes:
      - $CERT_FILE:/etc/nginx/certs/fullchain.pem:ro
      - $CERT_KEY:/etc/nginx/certs/privkey.pem:ro
      - ./nginxconf/https.conf:/etc/nginx/templates/default.conf.template:ro
    ports:
      - 443:443