version: "3.9"

services:
  server:
    build:
      target: prod
    environment:
      - SERVER_HOST_NAME=http://localhost
  nginx:
    build:
      dockerfile: Dockerfile
      target: nginx
    volumes:
      - $CERT_FILE:/etc/nginx/certs/fullchain.pem
      - $CERT_KEY:/etc/nginx/certs/privkey.pem
      - ./nginxconf/https.conf:/etc/nginx/templates/default.conf.template
    ports:
      - 80:80