version: "3.9"

services:
  server:
    build:
      context: ./django
      dockerfile: django.dockerfile
    environment:
      - SECRET=$SECRET
      - DEBUG=$DEBUG
      - HOSTNAME=$HOSTNAME
  
  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    environment:
      - HOSTNAME=$HOSTNAME
    ports:
      - 8080:443