version: "3.9"

services:
  server:
    build:
      context: ./django
      dockerfile: django.dockerfile
  
  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - 8080:8080