version: "3.9"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    environment:
      - SECRET=$SECRET
      - DEBUG=$DEBUG
      - SERVER_HOST_NAME=$SERVER_HOST_NAME
  redis:
    image: redis