version: "3.9"

services:
  server:
    build:
      context: ./django
      dockerfile: django.dockerfile
    environment:
      - SECRET=$SECRET
      - DEBUG=$DEBUG
      - HOSTNAME=$HOSTNAME
    volumes:
      - $DATABASE_FILE:/usr/app/src/db.sqlite3
  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    volumes:
      - $CERT_FILE:/etc/nginx/certs/fullchain.pem
      - $CERT_KEY:/etc/nginx/certs/privkey.pem
    environment:
      - HOSTNAME=$HOSTNAME
    ports:
      - 8080:443